---
# Ubuntu related OS tasks
- name: Add Kismet Key
  apt_key:
    url: https://www.kismetwireless.net/repos/kismet-release.gpg.key
    state: present

- name: Add Kismet Repo
  apt_repository:
    repo: deb https://www.kismetwireless.net/repos/apt/release/kali kali main
    state: present

apt install build-essential git libmicrohttpd-dev pkg-config zlib1g-dev libnl-3-dev libnl-genl-3-dev libcap-dev libpcap-dev libnm-dev libdw-dev libsqlite3-dev libprotobuf-dev libprotobuf-c-dev protobuf-compiler protobuf-c-compiler libsensors4-dev libusb-1.0.0-dev python3 python3-setuptools python3-protobuf python3-requests python3-numpy python3-serial python3-usb python3-dev librtlsdr0 libubertooth-dev libbtbb-dev


- name: Install Kismet 
  apt:
    pkg:
    - kismet
    - kismet-core 
    - kismet-capture-linux-bluetooth 
    - kismet-capture-linux-wifi 
    - kismet-capture-nrf-mousejack 
    - python-kismetcapturertl433 
    - python-kismetcapturertladsb 
    - python-kismetcapturertlamr 
    - python-kismetcapturefreaklabszigbee 
    - kismet-logtools
    update_cache: yes