---
# Ubuntu related OS tasks
- name: Add Kismet Key
  apt_key:
    url: https://www.kismetwireless.net/repos/kismet-release.gpg.key
    state: present

- name: Add Kismet Repo
  apt_repository:
    repo: deb https://www.kismetwireless.net/repos/apt/release/kali kali main
    state: present

- name: Install Kismet 
  apt:
    pkg:
    - kismet
    - kismet-core 
    - kismet-capture-linux-bluetooth 
    - kismet-capture-linux-wifi 
    - kismet-capture-nrf-mousejack 
    - python-kismetcapturertl433 
    - python-kismetcapturertladsb 
    - python-kismetcapturertlamr 
    - python-kismetcapturefreaklabszigbee 
    - kismet-logtools
    update_cache: yes